# Generated by Django 3.2.24 on 2024-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_historicalsharedfileupload_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studenttrainingworkflow',
            name='item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
