# Generated by Django 2.2.10 on 2020-04-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_TeamWorkflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAssessmentWorkflowCancellation',
            fields=[
                ('assessmentworkflowcancellation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.AssessmentWorkflowCancellation')),
                ('team_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_cancellations', to='workflow.TeamAssessmentWorkflow')),
            ],
            bases=('workflow.assessmentworkflowcancellation',),
        ),
    ]
