# Generated by Django 4.2.5 on 2023-09-27 11:59

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_assessmentworkflowstep_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentworkflow',
            name='status',
            field=model_utils.fields.StatusField(choices=[('peer', 'peer'), ('self', 'self'), ('training', 'training'), ('waiting', 'waiting'), ('done', 'done'), ('cancelled', 'cancelled')], default='peer', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
