[tox]
envlist = django42, django52, js, quality, docs
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    pytest

[testenv:django42]
runner = uv-venv-lock-runner
dependency_groups = django42
commands =
    pytest

[testenv:js]
runner = uv-venv-lock-runner
allowlist_externals = make
dependency_groups = django42
commands =
    make install-js
    make static
    make test-js

[testenv:docs]
runner = uv-venv-lock-runner
dependency_groups = doc
allowlist_externals = make
commands =
    doc8 docs/
    python -m build --wheel
    twine check dist/*
    make -C docs clean
    make -C docs html

[testenv:quality]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = src
allowlist_externals =
    make
    npm
dependency_groups = quality
commands =
    npm install jshint --no-save
    make quality
    python manage.py makemessages -l eo
    make check_translations_up_to_date
    make validate_translations
