# Generated by Django 6.0.4 on 2026-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_orareminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orareminder',
            name='reminder_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
