blank_issues_enabled: false
contact_links:
  - name: Open edX Community Support
    url: https://discuss.openedx.org/
    about: Please ask all questions, suggest all enhancements, and report all bugs here.
