# Generated by Django 2.2.24 on 2021-09-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_TeamWorkflows'),
        ('staffgrader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiongradinglock',
            name='staff_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assessment.StaffWorkflow'),
        ),
    ]
