# Generated by Django 2.2.24 on 2021-09-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffgrader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiongradinglock',
            name='submission_type',
        ),
    ]
