# Generated by Django 2.2.24 on 2021-10-27 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staffgrader', '0002_timezones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiongradinglock',
            name='submission_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
