# Generated by Django 2.2.24 on 2021-10-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffgrader', '0004_indexes_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiongradinglock',
            name='submission_uuid',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
