name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        toxenv: [quality, js, django42, django52]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "${{ matrix.python-version }}"
          enable-cache: true

      - name: Set env variable
        run: export AWS_CONFIG_FILE=/dev/null

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Install GNU gettext
        run: sudo apt-get install gettext

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Run Tests
        run: uv run tox -e ${{ matrix.toxenv }}

      - name: Run Coverage
        if: matrix.python-version == '3.12' && matrix.toxenv=='django42'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
